#! /usr/bin/env bash

./scripts/validation/fast_metrics.py -i results/VBGMM/Optimal_f1500/* -m samples/seq_index.json --map --nopal -o graphs/VBGMM/ -n "VBGMM_Optimal_f1500"
./scripts/validation/fast_metrics.py -i results/VBGMM/Optimal_f1500_bam/* -m samples/seq_index.json --map --nopal -o graphs/VBGMM/ -n "VBGMM_Optimal_f1500_bam"
./scripts/validation/fast_metrics.py -i results/VBGMM/Optimal_f1500_bam_nopal/* -m samples/seq_index.json --map --nopal -o graphs/VBGMM/ -n "VBGMM_Optimal_f1500_bam_nopal"
./scripts/validation/fast_metrics.py -i results/VBGMM/Optimal_f1500_cov/* -m samples/seq_index.json --map --nopal -o graphs/VBGMM/ -n "VBGMM_Optimal_f1500_cov"
./scripts/validation/fast_metrics.py -i results/VBGMM/Optimal_f1500_cov_nopal/* -m samples/seq_index.json --map --nopal -o graphs/VBGMM/ -n "VBGMM_Optimal_f1500_cov_nopal"
./scripts/validation/fast_metrics.py -i results/VBGMM/Optimal_f1500_bam_cov/* -m samples/seq_index.json --map --nopal -o graphs/VBGMM/ -n "VBGMM_Optimal_f1500_bam_cov"
./scripts/validation/fast_metrics.py -i results/VBGMM/Optimal_f1500_bam_cov_nopal/* -m samples/seq_index.json --map --nopal -o graphs/VBGMM/ -n "VBGMM_Optimal_f1500_bam_cov_nopal"

./scripts/validation/fast_metrics.py -i results/VBGMM/BIC_f1500/* -m samples/seq_index.json --map --nopal -o graphs/VBGMM/ -n "VBGMM_BIC_f1500"
./scripts/validation/fast_metrics.py -i results/VBGMM/BIC_f1500_nopal/* -m samples/seq_index.json --map --nopal -o graphs/VBGMM/ -n "VBGMM_BIC_f1500_nopal"
./scripts/validation/fast_metrics.py -i results/VBGMM/BIC_f1500_bam/* -m samples/seq_index.json --map --nopal -o graphs/VBGMM/ -n "VBGMM_BIC_f1500_bam"
./scripts/validation/fast_metrics.py -i results/VBGMM/BIC_f1500_bam_nopal/* -m samples/seq_index.json --map --nopal -o graphs/VBGMM/ -n "VBGMM_BIC_f1500_bam_nopal"
./scripts/validation/fast_metrics.py -i results/VBGMM/BIC_f1500_cd/* -m samples/seq_index.json --map --nopal -o graphs/VBGMM/ -n "VBGMM_BIC_f1500_cd"
./scripts/validation/fast_metrics.py -i results/VBGMM/BIC_f1500_cd_nopal/* -m samples/seq_index.json --map --nopal -o graphs/VBGMM/ -n "VBGMM_BIC_f1500_cd_nopal"
./scripts/validation/fast_metrics.py -i results/VBGMM/BIC_f1500_bam_cd/* -m samples/seq_index.json --map --nopal -o graphs/VBGMM/ -n "VBGMM_BIC_f1500_bam_cd"
./scripts/validation/fast_metrics.py -i results/VBGMM/BIC_f1500_bam_cd_nopal/* -m samples/seq_index.json --map --nopal -o graphs/VBGMM/ -n "VBGMM_BIC_f1500_bam_cd_nopal"

./scripts/validation/fast_metrics.py -i results/VBGMM/AIC_f1500/* -m samples/seq_index.json --map --nopal -o graphs/VBGMM/ -n "VBGMM_AIC_f1500"
./scripts/validation/fast_metrics.py -i results/VBGMM/AIC_f1500_nopal/* -m samples/seq_index.json --map --nopal -o graphs/VBGMM/ -n "VBGMM_AIC_f1500_nopal"
./scripts/validation/fast_metrics.py -i results/VBGMM/AIC_f1500_bam/* -m samples/seq_index.json --map --nopal -o graphs/VBGMM/ -n "VBGMM_AIC_f1500_bam"
./scripts/validation/fast_metrics.py -i results/VBGMM/AIC_f1500_bam_nopal/* -m samples/seq_index.json --map --nopal -o graphs/VBGMM/ -n "VBGMM_AIC_f1500_bam_nopal"
./scripts/validation/fast_metrics.py -i results/VBGMM/AIC_f1500_cd/* -m samples/seq_index.json --map --nopal -o graphs/VBGMM/ -n "VBGMM_AIC_f1500_cd"
./scripts/validation/fast_metrics.py -i results/VBGMM/AIC_f1500_cd_nopal/* -m samples/seq_index.json --map --nopal -o graphs/VBGMM/ -n "VBGMM_AIC_f1500_cd_nopal"
./scripts/validation/fast_metrics.py -i results/VBGMM/AIC_f1500_bam_cd/* -m samples/seq_index.json --map --nopal -o graphs/VBGMM/ -n "VBGMM_AIC_f1500_bam_cd"
./scripts/validation/fast_metrics.py -i results/VBGMM/AIC_f1500_bam_cd_nopal/* -m samples/seq_index.json --map --nopal -o graphs/VBGMM/ -n "VBGMM_AIC_f1500_bam_cd_nopal"

./scripts/validation/fast_metrics.py -i results/VBGMM/BIC_f1500_db/* -m samples/seq_index.json --map --nopal -o graphs/VBGMM/ -n "VBGMM_BIC_f1500_db"
./scripts/validation/fast_metrics.py -i results/VBGMM/BIC_f1500_nopal_db/* -m samples/seq_index.json --map --nopal -o graphs/VBGMM/ -n "VBGMM_BIC_f1500_nopal_db"
./scripts/validation/fast_metrics.py -i results/VBGMM/BIC_f1500_bam_db/* -m samples/seq_index.json --map --nopal -o graphs/VBGMM/ -n "VBGMM_BIC_f1500_bam_db"
./scripts/validation/fast_metrics.py -i results/VBGMM/BIC_f1500_bam_nopal_db/* -m samples/seq_index.json --map --nopal -o graphs/VBGMM/ -n "VBGMM_BIC_f1500_bam_nopal_db"
./scripts/validation/fast_metrics.py -i results/VBGMM/BIC_f1500_cd_db/* -m samples/seq_index.json --map --nopal -o graphs/VBGMM/ -n "VBGMM_BIC_f1500_cd_db"
./scripts/validation/fast_metrics.py -i results/VBGMM/BIC_f1500_cd_nopal_db/* -m samples/seq_index.json --map --nopal -o graphs/VBGMM/ -n "VBGMM_BIC_f1500_cd_nopal_db"
./scripts/validation/fast_metrics.py -i results/VBGMM/BIC_f1500_bam_cd_db/* -m samples/seq_index.json --map --nopal -o graphs/VBGMM/ -n "VBGMM_BIC_f1500_bam_cd_db"
./scripts/validation/fast_metrics.py -i results/VBGMM/BIC_f1500_bam_cd_nopal_db/* -m samples/seq_index.json --map --nopal -o graphs/VBGMM/ -n "VBGMM_BIC_f1500_bam_cd_nopal_db"

./scripts/validation/fast_metrics.py -i results/VBGMM/AIC_f1500/* -m samples/seq_index.json --map --nopal -o graphs/VBGMM/ -n "VBGMM_AIC_f1500"
./scripts/validation/fast_metrics.py -i results/VBGMM/AIC_f1500_nopal/* -m samples/seq_index.json --map --nopal -o graphs/VBGMM/ -n "VBGMM_AIC_f1500_nopal"
./scripts/validation/fast_metrics.py -i results/VBGMM/AIC_f1500_bam/* -m samples/seq_index.json --map --nopal -o graphs/VBGMM/ -n "VBGMM_AIC_f1500_bam"
./scripts/validation/fast_metrics.py -i results/VBGMM/AIC_f1500_bam_nopal/* -m samples/seq_index.json --map --nopal -o graphs/VBGMM/ -n "VBGMM_AIC_f1500_bam_nopal"
./scripts/validation/fast_metrics.py -i results/VBGMM/AIC_f1500_cd/* -m samples/seq_index.json --map --nopal -o graphs/VBGMM/ -n "VBGMM_AIC_f1500_cd"
./scripts/validation/fast_metrics.py -i results/VBGMM/AIC_f1500_cd_nopal/* -m samples/seq_index.json --map --nopal -o graphs/VBGMM/ -n "VBGMM_AIC_f1500_cd_nopal"
./scripts/validation/fast_metrics.py -i results/VBGMM/AIC_f1500_bam_cd/* -m samples/seq_index.json --map --nopal -o graphs/VBGMM/ -n "VBGMM_AIC_f1500_bam_cd"
./scripts/validation/fast_metrics.py -i results/VBGMM/AIC_f1500_bam_cd_nopal/* -m samples/seq_index.json --map --nopal -o graphs/VBGMM/ -n "VBGMM_AIC_f1500_bam_cd_nopal"

./scripts/validation/fast_metrics.py -i results/VBGMM/BIC_f1500_bam_weight/* -m samples/seq_index.json --map --nopal -o graphs/VBGMM/ -n "VBGMM_BIC_f1500_bam_weight"
./scripts/validation/fast_metrics.py -i results/VBGMM/BIC_f1500_bam_nopal_weight/* -m samples/seq_index.json --map --nopal -o graphs/VBGMM/ -n "VBGMM_BIC_f1500_bam_nopal_weight"
./scripts/validation/fast_metrics.py -i results/VBGMM/BIC_f1500_bam_cd_weight/* -m samples/seq_index.json --map --nopal -o graphs/VBGMM/ -n "VBGMM_BIC_f1500_bam_cd_weight"
./scripts/validation/fast_metrics.py -i results/VBGMM/BIC_f1500_bam_cd_nopal_weight/* -m samples/seq_index.json --map --nopal -o graphs/VBGMM/ -n "VBGMM_BIC_f1500_bam_cd_nopal_weight"
