#! /usr/bin/env bash

module load insilicoseq/1.1.1
module load megahit/1.1.4
module load bowtie/2.2.9
module load samtools/1.3.1
module load metabat/2.11.1
module load concoct
module load biopython
module load python/3.7.3
